<?php // ==== CONFIGURATION (CUSTOM) ==== //

// Specify custom configuration values in this file; these will override values in `functions-config-defaults.php`
// The general idea here is to allow for themes to be customized for specific installations

defined( 'VOIDX_SCRIPTS_PAGELOAD' )       || define( 'VOIDX_SCRIPTS_PAGELOAD', false );

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_content-full',
		'title' => 'Content Full',
		'fields' => array (
			array (
				'key' => 'field_56fe9d74d309e',
				'label' => 'Page Intro',
				'name' => 'page_intro',
				'type' => 'text',
				'instructions' => 'Add the page intro.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56fe9d88d309f',
				'label' => 'Page Title',
				'name' => 'page_title',
				'type' => 'text',
				'instructions' => 'Add the page title.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56fea194ac2c8',
				'label' => 'Full Item',
				'name' => 'full_item',
				'type' => 'repeater',
				'instructions' => 'Add the item.',
				'required' => 1,
				'sub_fields' => array (
					array (
						'key' => 'field_56fea1c6ac2ca',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'wysiwyg',
						'instructions' => 'Add the text',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
				),
				'row_min' => 2,
				'row_limit' => 6,
				'layout' => 'row',
				'button_label' => 'Add Item',
			),
			array (
				'key' => 'field_56feb1829c6af',
				'label' => 'Side Item',
				'name' => 'side_item',
				'type' => 'repeater',
				'instructions' => 'Add the site items.',
				'required' => 1,
				'sub_fields' => array (
					array (
						'key' => 'field_56feb1c29c6b0',
						'label' => 'Side Text',
						'name' => 'side_text',
						'type' => 'wysiwyg',
						'instructions' => 'Add the side text.',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
				),
				'row_min' => 1,
				'row_limit' => 3,
				'layout' => 'row',
				'button_label' => 'Add Side Item',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'index.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_content-list',
		'title' => 'Content List',
		'fields' => array (
			array (
				'key' => 'field_56fe9e0a00d50',
				'label' => 'Work Item',
				'name' => 'work_item',
				'type' => 'repeater',
				'instructions' => 'Add the work item.',
				'required' => 1,
				'sub_fields' => array (
					array (
						'key' => 'field_56fe9e3400d51',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => 'Add the link',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_56fe9e4200d52',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add the image',
						'required' => 1,
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_56fe9e5800d53',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => 'Add the title.',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_56fe9e6d00d54',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'textarea',
						'instructions' => 'Add the text.',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
				),
				'row_min' => 1,
				'row_limit' => 12,
				'layout' => 'row',
				'button_label' => 'Add Item',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'index.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_content-resume',
		'title' => 'Content Resume',
		'fields' => array (
			array (
				'key' => 'field_56fed1897e9eb',
				'label' => 'Work Title',
				'name' => 'work_title',
				'type' => 'text',
				'instructions' => 'Add work title.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56fec8247cef7',
				'label' => 'Resume Work',
				'name' => 'resume_work',
				'type' => 'repeater',
				'instructions' => 'Add a resume work item.',
				'required' => 1,
				'sub_fields' => array (
					array (
						'key' => 'field_56fec8427cef8',
						'label' => 'Company Name',
						'name' => 'company_name',
						'type' => 'text',
						'instructions' => 'Add the company name.',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_56fec8607cef9',
						'label' => 'Job Title',
						'name' => 'job_title',
						'type' => 'text',
						'instructions' => 'Add your job title.',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_56fec8727cefa',
						'label' => 'Dates',
						'name' => 'dates',
						'type' => 'text',
						'instructions' => 'Add the dates worked.',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_56fec8837cefb',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
						'instructions' => 'Add the description of the job.',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
				),
				'row_min' => 1,
				'row_limit' => 6,
				'layout' => 'row',
				'button_label' => 'Add Item',
			),
			array (
				'key' => 'field_56fed1ad7e9ec',
				'label' => 'Education Title',
				'name' => 'education_title',
				'type' => 'text',
				'instructions' => 'Add the education title.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56fec8a97cefc',
				'label' => 'Resume Education',
				'name' => 'resume_education',
				'type' => 'repeater',
				'instructions' => 'Add your education.',
				'required' => 1,
				'sub_fields' => array (
					array (
						'key' => 'field_56fec8c27cefd',
						'label' => 'Name of Institution',
						'name' => 'name_of_institution',
						'type' => 'text',
						'instructions' => 'Add the name of the institution',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_56fec8de7cefe',
						'label' => 'Achievements',
						'name' => 'achievements',
						'type' => 'text',
						'instructions' => 'Add the achievements received as a result.',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => 6,
				'layout' => 'row',
				'button_label' => 'Add item',
			),
			array (
				'key' => 'field_56febf4b11d71',
				'label' => 'Resume Side',
				'name' => 'resume_side',
				'type' => 'wysiwyg',
				'instructions' => 'Add the resume side content.',
				'required' => 1,
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'index.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
